import { Inter } from "next/font/google";
import "./styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Paperflow",
  // description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:dark`}>
        <main
          className="flex min-h-screen max-h-screen flex-col md:flex-row-reverse justify-between"
          style={{
            minHeight: "100dvh",
            maxHeight: "100dvh",
          }}
        >
          <div className={`flex-1 overflow-scroll`}>{children}</div>
          <div className="max-sm:shadow-inner md:border-r md:h-screen sticky top-0">
            M
          </div>
        </main>
      </body>
    </html>
  );
}
