import { Menu } from './components/menu'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col-reverse md:flex-row justify-between">
          <div className="max-sm:border-t md:border-r border-zinc-300">
            <Menu />
          </div>
          <div className='flex-1 p-2'>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
