export const metadata = {
  title: "Privacy Policy for Paperflow",
  // description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="relative flex flex-col place-items-center before:absolute before:h-[300px] before:w-[480px] before:-translate-x-1/2">
        <div>
          <h1>Privacy Policy for Paperflow</h1>
          <p>Effective Date: July 17, 2023</p>
          <p>
            Thank you for choosing Paperflow, a non-profit foundation dedicated
            to promoting academic discourse and knowledge sharing. This Privacy
            Policy outlines how we collect, use, and protect your personal
            information when you use our website or mobile application
            (&quot;the App&quot;) to read and comment on academic preprints
            published under Creative Commons licenses, such as those from
            arXiv.org. By using the App, you consent to the practices described
            in this Privacy Policy.
          </p>

          <h2>Information We Collect</h2>
          <h3>1.1 Personal Information for Registered Users</h3>
          <p>
            When you register with Paperflow, we collect certain personal
            information to provide you with an enhanced user experience and
            fulfill our legal obligations under the General Data Protection
            Regulation (GDPR). This may include your name, email address, and
            other necessary contact information.
          </p>

          <h3>1.2 Usage Information</h3>
          <p>
            For registered users, we collect and log information about your
            activity within the App, such as the preprints you read, the
            comments you make, and the conversations you participate in. This
            information is essential to maintain the functionality of the App
            and to improve our services. We handle this information with the
            utmost care and in compliance with the GDPR.
          </p>

          <h3>1.3 Information for Unregistered Users</h3>
          <p>
            To ensure your privacy, we do not collect any personally
            identifiable information from unregistered users. We respect your
            decision to use the App anonymously, and we do not track or log any
            activity for unregistered users.
          </p>

          <h2>Use of Information</h2>
          <h3>2.1 Providing and Improving Services</h3>
          <p>
            We use the information collected to provide you with the requested
            services, enhance your user experience, and improve the App&apos;s
            functionality. This may include personalizing your content
            recommendations, optimizing our search algorithms, and implementing
            new features based on user feedback.
          </p>

          <h3>2.2 Compliance with Legal Obligations</h3>
          <p>
            For registered users, we process your personal information as
            required by law to fulfill our legal obligations, including but not
            limited to compliance with the GDPR. This processing allows us to
            provide you with the rights afforded by the GDPR, such as the right
            to access, correct, or delete your personal data.
          </p>

          <h2>Data Storage and Sharing</h2>
          <h3>3.1 Data Storage</h3>
          <p>
            All logged user data, including comments, conversations, and any
            content posted through the App, will become part of the commons. To
            ensure long-term preservation and transparency, this data will be
            stored on a public blockchain. By contributing to the commons, you
            acknowledge that your information may be publicly accessible and
            retained indefinitely.
          </p>

          <h3>3.2 Third-Party Service Providers</h3>
          <p>
            We may engage trusted third-party service providers to assist us in
            delivering and improving our services. These providers may have
            access to your personal information but will only process it as
            necessary to perform their designated tasks on our behalf. We ensure
            that any third-party service providers adhere to the same level of
            data protection as outlined in this Privacy Policy.
          </p>

          <h3>3.3 Legal Compliance and Protection</h3>
          <p>
            We may disclose personal information when required by law or if we
            believe, in good faith, that such action is necessary to protect our
            rights, comply with a judicial proceeding, court order, or other
            legal processes.
          </p>

          <h2>Security Measures</h2>
          <h3>4.1 Data Security</h3>
          <p>
            We implement appropriate technical and organizational measures to
            safeguard your personal information against unauthorized access,
            disclosure, alteration, or destruction. We regularly review and
            update our security practices to ensure the highest level of
            protection.
          </p>

          <h3>4.2 User Responsibility</h3>
          <p>
            While we strive to protect your personal information, we encourage
            you to maintain the security of your account and exercise caution
            when interacting with the App. Please refrain from sharing sensitive
            information or using easily guessable passwords.
          </p>

          <h2>Creative Commons Principles</h2>
          <h3>5.1 Promoting Openness</h3>
          <p>
            Paperflow adheres to the Creative Commons principles, promoting
            openness, collaboration, and knowledge sharing within the academic
            community. We respect the intellectual property rights of content
            creators and encourage responsible use of the materials available
            through the App.
          </p>

          <h3>5.2 Non-Profit Nature</h3>
          <p>
            Paperflow is a non-profit foundation, committed to serving the
            academic community without commercial interests. Our mission is to
            foster open discourse and contribute to the advancement of
            knowledge, ensuring equitable access to educational resources.
          </p>

          <h2>Contact Us</h2>
          <p>
            If you have any questions, concerns, or requests regarding your
            privacy or this Privacy Policy, please contact us at [email
            address]. We will respond to your inquiry as soon as possible.
          </p>

          <h2>Updates to this Privacy Policy</h2>
          <p>
            We may update this Privacy Policy from time to time to reflect
            changes in our practices or legal obligations. We will notify you of
            any material changes by posting a prominent notice within the App or
            by sending you a direct communication. We encourage you to review
            this Privacy Policy periodically to stay informed about how we
            handle your personal information.
          </p>

          <p>
            By continuing to use the App after such changes have been made, you
            acknowledge and agree to the updated Privacy Policy.
          </p>
          <p>
            Thank you for trusting Paperflow with your personal information. We
            remain committed to protecting your privacy and facilitating the
            open exchange of knowledge.
          </p>

          <p className="mt-4 italic text-right">Paperflow Foundation</p>
        </div>
      </div>
    </main>
  );
}
