import { Anek_Malayalam } from "next/font/google";
import "src/styles/globals.css";
import { MainMenu } from "src/components/menu";

const font = Anek_Malayalam({ subsets: ["latin"], display: "swap" });
const lightModeEnabled = false;

export const metadata = {
  title: "Paperflow",
  // description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${font.className} flex justify-center ${
          lightModeEnabled ? "dark:dark" : "dark"
        }`}
      >
        <main
          className="min-h-screen max-h-screen w-full max-w-[640px] flex flex-col"
          style={{
            minHeight: "100dvh",
            maxHeight: "100dvh",
          }}
        >
          <div className={`flex-1 overflow-scroll px-4`}>{children}</div>

          <div className="py-4">
            <MainMenu />
          </div>
        </main>
      </body>
    </html>
  );
}
