import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head>
        <title>Ingestion app</title>
      </head>
      <body className="overflow-y-scroll bg-zinc-900">
        <div className="p-8">
          <div className="space-y-6">
            <div className="rounded-xl border border-zinc-800 bg-black p-8">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
